services:
  - type: web
    name: skladusa-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFY_TOKEN
        value: skladusa_secret_2024
